apiVersion: v1
kind: Service
metadata:
  name: |-
    {{ .Release.Name }}
  labels:
    name: |-
      {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.containerPort }}
    - name: https
      port: 443
      protocol: TCP
      targetPort: {{ .Values.containerPort }}
  selector:
    app: |-
      {{ .Release.Name }}
