repoUrl: 105618632367.dkr.ecr.us-east-1.amazonaws.com
tag: latest
httpEndpoint: gql-docs.dmp.mediajel.ninja
certificateArn: arn:aws:acm:us-east-1:105618632367:certificate/af54473c-845a-495b-ae6d-8cba77eb8b23
global:
  environment: STAGE
cpuRequest: 0.5
cpuLimit: 0.5
memoryRequest: 1Gi
memoryLimit: 1Gi
environment: STAGING
instancegroup: big-nodes
nextPublicGqlEndpoint: http://graphql-dojo.dmp.mediajel.ninja/

ingress:
  enabled: true

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 80
