repoUrl: 738466439161.dkr.ecr.us-east-1.amazonaws.com
tag: latest
httpEndpoint: gql-docs.dmp.cnna.io
certificateArn: arn:aws:acm:us-east-1:738466439161:certificate/982a5b7b-13ba-4d72-81c3-43784cefd372
global:
  environment: PRODUCTION
containerPort: 3000
cpuRequest: 1
cpuLimit: 1
memoryRequest: 2Gi
memoryLimit: 2Gi
environment: PRODUCTION
instancegroup: big-nodes
nextPublicGqlEndpoint: http://graphql.dmp.cnna.io/

ingress:
  enabled: true

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 80
